### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by tsteinholz** [LinkLabs/network_tester#1]
When compiling this in the terminal using the `make` command, I get the following error.

`make: *** No rule to make target `build/ll_ifc_no_mac.o', needed by `exe/network_tester.elf'.  Stop.`

The only line I changed in the MakeFile is on line 32 [`LINUXCS    ?= /opt/gcc-arm-none-eabi-5_2-2015q4`] where i changed my compiler location which i needed to do to get anything to compile obviously. The build didn't produce an elf or a bin file in the exe folder, only some object code in the build folder.

**Comment by rlunall** [comment]
I added the missing files required by recent changes to ll_ifc, the library used to communicate with the Symphony module.  Thanks!
